name: test-actions

on:
  push:
    branches:
      - master

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up node
        uses: actions/openapi-to-json-schema@v0.0.2
      - name: List openapi specification file
        run: |
          ls -al openapi.yml
