name: test-actions

on:
  push:
    branches:
      - master

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: openapi to json schema
        uses: christrewin/openapi-to-json-schema@v0.0.4
      - name: List openapi specification file
        run: |
          ls -al openapi.yml
