name: test-actions

on:
  push:
    branches:
      - master

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: openapi-to-json-schema
        name: openapi to json schema
        uses: christrewin/openapi-to-json-schema@v0.0.7
        with:
          # specification-url: 'https://dev.telstra.com/sites/default/files/redocs/1620871323/messaging-api-swagger_0.yaml'
          specification-url: 'https://devxspecs.s3-ap-southeast-2.amazonaws.com/openapi.yaml'
      - id: list-spec-file
      - name: List spec file
        run: |
          ls -al \
          docker --version
        shell: bash
