name: test-actions

on:
  push:
    branches:
      - master

jobs:
  openapi-to-json-schema:
    runs-on: ubuntu-latest
    steps:
      - id: openapi-to-json-schema
        name: openapi to json schema
        uses: christrewin/openapi-to-json-schema@v0.0.11
        with:
          # specification-url: 'https://dev.telstra.com/sites/default/files/redocs/1620871323/messaging-api-swagger_0.yaml'
          specification-url: 'https://devxspecs.s3-ap-southeast-2.amazonaws.com/openapi.yaml'
      - id: list-file
        name: List file
        run: |
          value=`ls -al ${{ github.workspace }}/openapi/${{ steps.openapi-to-json-schema.outputs.json-schema-file }}`
          echo The file is $value
        shell: bash
      - name: Upload openapi.json
        uses: actions/upload-artifact@v2
        with:
          name: openapi.json
          path: ${{ github.workspace }}/openapi/${{ steps.openapi-to-json-schema.outputs.json-schema-file }}
  checkout-repo:
    runs-on: ubuntu-latest
    needs:
      - openapi-to-json-schema
    steps:
      - id: download-artifact
        name: openapi.json
        uses: actions/download-artifact@v2
        with:
          name: openapi.json
      - id: list-file
        name: List file
        run: |
          value=`cat ${{ github.workspace }}/${{ steps.download-artifact.name }}`
          echo The file is $value
        shell: bash
  # build-project:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - checkout-repo
  #   steps:
  #     - name: Download openapi.json
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: openapi.json
  #     - id: list-file
  #       name: List file
  #       run: |
  #         value=`file ${{ github.workspace }}/${{ steps.openapi-to-json-schema.outputs.json-schema-file }}`
  #         echo The file is $value
  #       shell: bash
  # package-project:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-project
  #   steps:
  #     - name: Download openapi.json
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: openapi.json
  #     - id: list-file
  #       name: List file
  #       run: |
  #         value=`file ${{ github.workspace }}/${{ steps.openapi-to-json-schema.outputs.json-schema-file }}`
  #         echo The file is $value
  #       shell: bash
